"""empty message

Revision ID: 07236ed5b186
Revises: b2b899028b84
Create Date: 2023-07-10 22:02:19.154781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07236ed5b186'
down_revision = 'b2b899028b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('XcOS_sign_in',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sign_in_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['XcOS_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('XcOS_sign_in')
    # ### end Alembic commands ###
