"""empty message

Revision ID: 42a7612b492b
Revises: 478b661316ad
Create Date: 2023-07-18 22:45:57.776770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42a7612b492b'
down_revision = '478b661316ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_product', schema=None) as batch_op:
        batch_op.alter_column('simple_description',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=25),
               existing_nullable=True)
        batch_op.alter_column('img_src',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_product', schema=None) as batch_op:
        batch_op.alter_column('img_src',
               existing_type=sa.String(length=255),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
        batch_op.alter_column('simple_description',
               existing_type=sa.Text(length=25),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
