"""empty message

Revision ID: 478b661316ad
Revises: 8f0d90caf70e
Create Date: 2023-07-18 22:45:28.196193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '478b661316ad'
down_revision = '8f0d90caf70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_src', sa.Text(length=65535), nullable=True))
        batch_op.alter_column('simple_description',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=25),
               existing_nullable=True)
        batch_op.drop_column('img_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('simple_description',
               existing_type=sa.Text(length=25),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
        batch_op.drop_column('img_src')

    # ### end Alembic commands ###
