"""empty message

Revision ID: 653e4424766a
Revises: 4931d6f79667
Create Date: 2023-07-13 21:06:11.783696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653e4424766a'
down_revision = '4931d6f79667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('XcOS_notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('XcOS_notice')
    # ### end Alembic commands ###
