"""empty message

Revision ID: 8f0d90caf70e
Revises: 42090be46538
Create Date: 2023-07-17 21:58:42.087943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f0d90caf70e'
down_revision = '42090be46538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_path', sa.String(length=255), nullable=True))
        batch_op.alter_column('simple_description',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=25),
               existing_nullable=True)
        batch_op.drop_column('img_img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_img', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('simple_description',
               existing_type=sa.Text(length=25),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
        batch_op.drop_column('img_path')

    # ### end Alembic commands ###
