"""empty message

Revision ID: aa75a51172be
Revises: 653e4424766a
Create Date: 2023-07-13 22:29:31.540561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa75a51172be'
down_revision = '653e4424766a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('show_on_homepage', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_notice', schema=None) as batch_op:
        batch_op.drop_column('show_on_homepage')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
