"""empty message

Revision ID: b875587fdf46
Revises: aa75a51172be
Create Date: 2023-07-13 23:57:10.817709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b875587fdf46'
down_revision = 'aa75a51172be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('simple_description', sa.Text(length=25), nullable=True))
        batch_op.add_column(sa.Column('sales', sa.Integer(), nullable=True))
        batch_op.drop_column('product_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('sales')
        batch_op.drop_column('simple_description')

    # ### end Alembic commands ###
