"""empty message

Revision ID: c7d636e46930
Revises: 749e9077d76f
Create Date: 2023-07-15 14:07:17.333150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7d636e46930'
down_revision = '749e9077d76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_product', schema=None) as batch_op:
        batch_op.alter_column('simple_description',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=25),
               existing_nullable=True)

    with op.batch_alter_table('XcOS_sign_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('integral', sa.Integer(), nullable=False))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_sign_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', mysql.DECIMAL(precision=5, scale=2), nullable=False))
        batch_op.drop_column('integral')

    with op.batch_alter_table('XcOS_product', schema=None) as batch_op:
        batch_op.alter_column('simple_description',
               existing_type=sa.Text(length=25),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
