"""empty message

Revision ID: c9137cccf02b
Revises: d09aef52a32d
Create Date: 2023-07-17 20:17:15.108059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9137cccf02b'
down_revision = 'd09aef52a32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approval_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approval_info', sa.String(length=255), nullable=True))
        batch_op.alter_column('simple_description',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_product', schema=None) as batch_op:
        batch_op.alter_column('simple_description',
               existing_type=sa.Text(length=25),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)
        batch_op.drop_column('approval_info')
        batch_op.drop_column('approval_status')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
