"""empty message

Revision ID: e956bb7881d6
Revises: cad2e4ae3ed4
Create Date: 2023-07-23 15:39:24.165529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e956bb7881d6'
down_revision = 'cad2e4ae3ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_balance', sa.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('seller_balance', sa.DECIMAL(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('XcOS_product', schema=None) as batch_op:
        batch_op.alter_column('simple_description',
               existing_type=mysql.TINYTEXT(),
               type_=sa.Text(length=25),
               existing_nullable=True)
        batch_op.drop_column('buyer_balance')
        batch_op.drop_column('seller_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('XcOS_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_balance', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('buyer_balance', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.alter_column('simple_description',
               existing_type=sa.Text(length=25),
               type_=mysql.TINYTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('XcOS_order_detail', schema=None) as batch_op:
        batch_op.drop_column('seller_balance')
        batch_op.drop_column('buyer_balance')

    # ### end Alembic commands ###
